version: '3.8'
services:
  sortr-server:
    build: ./server
    depends_on:
      - mongodb
      - minio
    volumes:
      - ./server:/usr/src/sortr
      - sortr_node_modules:/usr/src/sortr/node_modules
    command: yarn dev
    ports:
      - '3001:3001'
    environment:
      NODE_ENV: development
      MONGODB_CONNECTION: mongodb://mongodb:27017/sortr-dev
      MONGODB_TEST_CONNECTION: mongodb://mongodb:27017/sortr-test
      SORTR_SERVER_PORT: 3001
      JWT_SECRET: 55AEC74CA0A65E3291D135AA234F4127D9DAAC60CA221BFE6AFAD8EA33CE97AD
      JWT_ACCESS_EXPIRES_MINUTES: 60
      JWT_REFRESH_EXPIRES_DAYS: 5
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
  minio:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
volumes:
  sortr_node_modules:
  mongodb_data:
  mongodb_config:
  minio_data:
