version: '3.8'
services:
  sortr-server:
    build:
      context: ./server
      target: dev
    depends_on:
      - mongodb
    volumes:
      - ./server:/server
    command: npm run dev
    ports:
      - '8000:8000'
    environment:
      NODE_ENV: development
      MONGODB_CONNECTION: mongodb://mongodb:27017/sortr-dev
      MONGODB_TEST_CONNECTION: mongodb://mongodb:27017/sortr-test
      SORTR_SERVER_PORT: 8000
  mongodb:
    image: mongo
    restart: always
    ports:
      - '27017:27017'
    volumes:
      - mongodb_data:/data/db
      - mongodb_config:/data/configdb
  minio:
    image: quay.io/minio/minio
    ports:
      - '9000:9000'
      - '9001:9001'
    volumes:
      - minio_data:/data
    command: minio server /data --console-address ":9001"
volumes:
  mongodb_data:
  mongodb_config:
  minio_data:
